# Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
# Framework • revision 68bfaea224 (7 days ago) • 2024-03-20 15:36:31 -0700
# Engine • revision a5c24f538d
# Tools • Dart 3.3.2 • DevTools 2.31.1

name: tmdb_chillflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  font_awesome_icon_class: ^0.0.6
  freezed: ^2.4.7
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  logger: ^2.1.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - flutter.env
