name: chillflix2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  firebase_auth: ^4.17.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.7.0
  freezed: ^2.4.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - flutter.env
