// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzYn6Gtz_Psysxu2KQaxekTx5K6gGhIQ',
    appId: '1:635286634976:web:174527cd0047959d88eb85',
    messagingSenderId: '635286634976',
    projectId: 'chillflix-5e920',
    authDomain: 'chillflix-5e920.firebaseapp.com',
    storageBucket: 'chillflix-5e920.appspot.com',
    measurementId: 'G-KD0J4XRPZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVXYfC7Etsdbix9rprNSrjLm9zFOCsu4',
    appId: '1:635286634976:android:f05d76b8aba5f24788eb85',
    messagingSenderId: '635286634976',
    projectId: 'chillflix-5e920',
    storageBucket: 'chillflix-5e920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9HD_JSFUsJECUdixZS32eGIgkqlbUvIU',
    appId: '1:635286634976:ios:8c13bea808649ec388eb85',
    messagingSenderId: '635286634976',
    projectId: 'chillflix-5e920',
    storageBucket: 'chillflix-5e920.appspot.com',
    iosClientId: '635286634976-8tep6795cp4pruf1qfo3ag1gllki6qpg.apps.googleusercontent.com',
    iosBundleId: 'com.kshitijcodecraft.chillflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9HD_JSFUsJECUdixZS32eGIgkqlbUvIU',
    appId: '1:635286634976:ios:92ee694975bef56588eb85',
    messagingSenderId: '635286634976',
    projectId: 'chillflix-5e920',
    storageBucket: 'chillflix-5e920.appspot.com',
    iosClientId: '635286634976-i7vdpdpvr2obh911k43sc1ngv1147gn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chillflix2.RunnerTests',
  );
}
